[theme]
primaryColor = "#7F77DD"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1C24"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false